/**
 * @name validateMaterialsIndividuals
 * @description
 *
 * This validation expression addresses an issue in the model where a material can
 * be linked to one or more individual but not for all material types. By using this
 * validation expression, we can restrict this for subclasses.
 *
 * The alternative option is to create separate columns in the model, but we would like
 * to avoid doings this at the moment; however, we may decide to do this at some future
 * timepoint.
 *
 * @param {string} tableclass value generated by mg_tableclass
 * @param {array} individuals individuals column input if defined
 *
 * @example
 *
 * ```js
 * validateIndividuals('Samples', [{...}, {...}]) // returns error
 * validateIndividuals('Samples', [{...}]) // returns true
 * validateIndividuals('Files', [{...}]) // returns true
 * validateIndividuals('Files', [{...}, {...}]) // returns true
 * ```
 */
export default function validateIndividuals(tableclass, individuals) {
  const samplesTablePattern = /(.Samples+)/;
  const hasMoreThanOne = individuals && individuals.length > 1;

  if (tableclass.endsWith(".Individual consent") && hasMoreThanOne) {
    return "Consent can only be linked to one individual";
  } else if (samplesTablePattern.test(samplesTablePattern) && hasMoreThanOne) {
    return "Samples can only be linked to one individual";
  } else {
    return true;
  }
}
